module.exports = {
  EXAMPLE: "EXAMPLE",
  HOME: "HOME",
  HEADER: "HEADER",
  FOOTER: "FOOTER",
  HELLOWORLD: "HELLOWORLD",
  STAGE: "STAGE",
  LOCALE: "LOCALE",
  CAR: "CAR",
  QUICKENTRYLEVEL: "QUICKENTRYLEVEL"
};
